USE cookDB;
CREATE TABLE TBL1
( a INT PRIMARY KEY,
b INT,
c INT
);

SHOW INDEX FROM TBL1;

CREATE TABLE TBL2
( a INT PRIMARY KEY,
b INT UNIQUE,
c INT UNIQUE,
d INT
);
SHOW INDEX FROM TBL2;

CREATE TABLE TBL3
( a INT UNIQUE,
b INT UNIQUE,
c INT UNIQUE,
d INT
);
SHOW INDEX FROM TBL3;

CREATE TABLE TBL4
( a INT UNIQUE NOT NULL,
b INT UNIQUE,
c INT UNIQUE,
d INT
);
SHOW INDEX FROM TBL4;

CREATE TABLE TBL5
( a INT UNIQUE NOT NULL,
b INT UNIQUE,
c INT UNIQUE,
d INT PRIMARY KEY
);
SHOW INDEX FROM TBL5;

CREATE DATABASE IF NOT EXISTS testDB;
USE testDB;
DROP TABLE IF EXISTS userTBL;
CREATE TABLE userTBL
( userID char(8) NOT NULL PRIMARY KEY,
userName varchar(10) NOT NULL,
birthYear int NOT NULL,
addr char(2) NOT NULL
);

INSERT INTO userTBL VALUES ('YJS', '유재석', 1972, '서울');
INSERT INTO userTBL VALUES ('KHD', '강호동', 1970, '경북');
INSERT INTO userTBL VALUES ('KKJ', '김국진', 1965, '서울');
INSERT INTO userTBL VALUES ('KYM', '김용만', 1967, '서울');
INSERT INTO userTBL VALUES ('KJD', '김제동', 1974, '경남');
SELECT * FROM userTBL;

ALTER TABLE userTBL DROP PRIMARY KEY;
ALTER TABLE userTBL
ADD CONSTRAINT pk_userName PRIMARY KEY (userName);
SELECT * FROM userTBL;